services:
  dpsim:
    image: soullessblob/enertef-sim:latest
    environment:
      VILLAS_PAYLOAD_FILE: /config/payload.json
    volumes:
      - ./payload.json:/config/payload.json
    privileged: true
    stdin_open: true
    tty: true
